//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.flows

import kotlinx.coroutines.flow.Flow
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.td.libcore.telegram.TdApi
import org.drinkless.td.libcore.telegram.TdApi.UpdateAccentColors
import org.drinkless.td.libcore.telegram.TdApi.UpdateProfileAccentColors

/**
 * emits [UpdateAccentColors] if the list of supported accent colors has changed.
 */
fun TelegramFlow.accentColorsFlow(): Flow<UpdateAccentColors> = this.getUpdatesFlowOfType()

/**
 * emits [UpdateProfileAccentColors] if the list of supported accent colors for user profiles has
 * changed.
 */
fun TelegramFlow.profileAccentColorsFlow(): Flow<UpdateProfileAccentColors> =
    this.getUpdatesFlowOfType()
