//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.flows

import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.td.libcore.telegram.TdApi
import org.drinkless.td.libcore.telegram.TdApi.ForumTopicInfo
import org.drinkless.td.libcore.telegram.TdApi.UpdateForumTopic

/**
 * emits info [ForumTopicInfo] if basic information about a topic in a forum chat was changed.
 */
fun TelegramFlow.forumTopicInfoFlow(): Flow<ForumTopicInfo> =
    this.getUpdatesFlowOfType<TdApi.UpdateForumTopicInfo>()
    .mapNotNull { it.info }

/**
 * emits [UpdateForumTopic] if information about a topic in a forum chat was changed.
 */
fun TelegramFlow.forumTopicFlow(): Flow<UpdateForumTopic> = this.getUpdatesFlowOfType()
