//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.flows

import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.td.libcore.telegram.TdApi
import org.drinkless.td.libcore.telegram.TdApi.PaidReactionType
import org.drinkless.td.libcore.telegram.TdApi.ReactionType

/**
 * emits [ReactionType] if the type of default reaction has changed.
 */
fun TelegramFlow.defaultReactionTypeFlow(): Flow<ReactionType> =
    this.getUpdatesFlowOfType<TdApi.UpdateDefaultReactionType>()
    .mapNotNull { it.reactionType }

/**
 * emits type [PaidReactionType] if the type of default paid reaction has changed.
 */
fun TelegramFlow.defaultPaidReactionTypeFlow(): Flow<PaidReactionType> =
    this.getUpdatesFlowOfType<TdApi.UpdateDefaultPaidReactionType>()
    .mapNotNull { it.type }
