//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.flows

import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.td.libcore.telegram.TdApi
import org.drinkless.tdlib.TdApi.Story
import org.drinkless.tdlib.TdApi.UpdateStoryDeleted
import org.drinkless.tdlib.TdApi.UpdateStoryPostFailed
import org.drinkless.tdlib.TdApi.UpdateStoryPostSucceeded
import org.drinkless.tdlib.TdApi.UpdateStoryStealthMode

/**
 * emits [Story] if a story was changed.
 */
fun TelegramFlow.storyFlow(): Flow<Story> = this.getUpdatesFlowOfType<TdApi.UpdateStory>()
    .mapNotNull { it.story }

/**
 * emits [UpdateStoryDeleted] if a story became inaccessible.
 */
fun TelegramFlow.storyDeletedFlow(): Flow<UpdateStoryDeleted> = this.getUpdatesFlowOfType()

/**
 * emits [UpdateStoryPostSucceeded] if a story has been successfully posted.
 */
fun TelegramFlow.storyPostSucceededFlow(): Flow<UpdateStoryPostSucceeded> =
    this.getUpdatesFlowOfType()

/**
 * emits [UpdateStoryPostFailed] if a story failed to post. If the story posting is canceled, then
 * updateStoryDeleted will be received instead of this update.
 */
fun TelegramFlow.storyPostFailedFlow(): Flow<UpdateStoryPostFailed> = this.getUpdatesFlowOfType()

/**
 * emits [UpdateStoryStealthMode] if story stealth mode settings have changed.
 */
fun TelegramFlow.storyStealthModeFlow(): Flow<UpdateStoryStealthMode> = this.getUpdatesFlowOfType()
