//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.flows

import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.td.libcore.telegram.TdApi
import org.drinkless.tdlib.TdApi.Supergroup
import org.drinkless.tdlib.TdApi.UpdateSupergroupFullInfo

/**
 * emits [Supergroup] if some data of a supergroup or a channel has changed. This update is
 * guaranteed to come before the supergroup identifier is returned to the application.
 */
fun TelegramFlow.supergroupFlow(): Flow<Supergroup> =
    this.getUpdatesFlowOfType<TdApi.UpdateSupergroup>()
    .mapNotNull { it.supergroup }

/**
 * emits [UpdateSupergroupFullInfo] if some data in supergroupFullInfo has been changed.
 */
fun TelegramFlow.supergroupFullInfoFlow(): Flow<UpdateSupergroupFullInfo> =
    this.getUpdatesFlowOfType()
