//
// NOTE: THIS FILE IS AUTO-GENERATED by the "ExtensionsGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.extensions

import kotlin.Boolean
import kotlin.ByteArray
import kotlin.Int
import kotlin.Long
import kotlin.LongArray
import kotlin.String
import kotlinx.telegram.core.TelegramFlow
import kotlinx.telegram.coroutines.banGroupCallParticipants
import kotlinx.telegram.coroutines.decryptGroupCallData
import kotlinx.telegram.coroutines.encryptGroupCallData
import kotlinx.telegram.coroutines.endGroupCall
import kotlinx.telegram.coroutines.endGroupCallRecording
import kotlinx.telegram.coroutines.endGroupCallScreenSharing
import kotlinx.telegram.coroutines.getGroupCall
import kotlinx.telegram.coroutines.getVideoChatInviteLink
import kotlinx.telegram.coroutines.getVideoChatStreamSegment
import kotlinx.telegram.coroutines.getVideoChatStreams
import kotlinx.telegram.coroutines.inviteGroupCallParticipant
import kotlinx.telegram.coroutines.inviteVideoChatParticipants
import kotlinx.telegram.coroutines.joinVideoChat
import kotlinx.telegram.coroutines.leaveGroupCall
import kotlinx.telegram.coroutines.loadGroupCallParticipants
import kotlinx.telegram.coroutines.revokeGroupCallInviteLink
import kotlinx.telegram.coroutines.sendGroupCallMessage
import kotlinx.telegram.coroutines.setGroupCallParticipantIsSpeaking
import kotlinx.telegram.coroutines.setGroupCallParticipantVolumeLevel
import kotlinx.telegram.coroutines.setVideoChatTitle
import kotlinx.telegram.coroutines.startGroupCallRecording
import kotlinx.telegram.coroutines.startGroupCallScreenSharing
import kotlinx.telegram.coroutines.startScheduledVideoChat
import kotlinx.telegram.coroutines.toggleGroupCallCanSendMessages
import kotlinx.telegram.coroutines.toggleGroupCallIsMyVideoEnabled
import kotlinx.telegram.coroutines.toggleGroupCallIsMyVideoPaused
import kotlinx.telegram.coroutines.toggleGroupCallParticipantIsHandRaised
import kotlinx.telegram.coroutines.toggleGroupCallParticipantIsMuted
import kotlinx.telegram.coroutines.toggleGroupCallScreenSharingIsPaused
import kotlinx.telegram.coroutines.toggleVideoChatEnabledStartNotification
import kotlinx.telegram.coroutines.toggleVideoChatMuteNewParticipants
import org.drinkless.tdlib.TdApi
import org.drinkless.tdlib.TdApi.FormattedText
import org.drinkless.tdlib.TdApi.GroupCall
import org.drinkless.tdlib.TdApi.GroupCallDataChannel
import org.drinkless.tdlib.TdApi.GroupCallJoinParameters
import org.drinkless.tdlib.TdApi.GroupCallVideoQuality
import org.drinkless.tdlib.TdApi.MessageSender

/**
 * Interface for access [TdApi.GroupCall] extension functions. Can be used alongside with other
 * extension interfaces of the package. Must contain [TelegramFlow] instance field to access its
 * functionality
 */
interface GroupCallKtx : BaseKtx {
  /**
   * Instance of the [TelegramFlow] connecting extensions to the Telegram Client
   */
  override val api: TelegramFlow

  /**
   * Suspend function, which bans users from a group call not bound to a chat; requires
   * groupCall.isOwned. Only the owner of the group call can invite the banned users back.
   *
   * @param userIds Identifiers of group call participants to ban; identifiers of unknown users from
   * the update updateGroupCallParticipants can be also passed to the method.
   */
  suspend fun GroupCall.banParticipants(userIds: LongArray?) = api.banGroupCallParticipants(this.id,
      userIds)

  /**
   * Suspend function, which decrypts group call data received by tgcalls.
   *
   * @param participantId Identifier of the group call participant, which sent the data.  
   * @param dataChannel Data channel for which data was encrypted; pass null if unknown.  
   * @param data Data to decrypt.
   *
   * @return [TdApi.Data] Contains some binary data.
   */
  suspend fun GroupCall.decryptData(
    participantId: MessageSender?,
    dataChannel: GroupCallDataChannel?,
    data: ByteArray?
  ) = api.decryptGroupCallData(this.id, participantId, dataChannel, data)

  /**
   * Suspend function, which encrypts group call data before sending them over network using
   * tgcalls.
   *
   * @param dataChannel Data channel for which data is encrypted.  
   * @param data Data to encrypt.  
   * @param unencryptedPrefixSize Size of data prefix that must be kept unencrypted.
   *
   * @return [TdApi.Data] Contains some binary data.
   */
  suspend fun GroupCall.encryptData(
    dataChannel: GroupCallDataChannel?,
    data: ByteArray?,
    unencryptedPrefixSize: Int
  ) = api.encryptGroupCallData(this.id, dataChannel, data, unencryptedPrefixSize)

  /**
   * Suspend function, which ends a group call. Requires groupCall.canBeManaged right for video
   * chats or groupCall.isOwned otherwise.
   */
  suspend fun GroupCall.end() = api.endGroupCall(this.id)

  /**
   * Suspend function, which ends recording of an active group call; for video chats only. Requires
   * groupCall.canBeManaged right.
   */
  suspend fun GroupCall.endRecording() = api.endGroupCallRecording(this.id)

  /**
   * Suspend function, which ends screen sharing in a joined group call.
   */
  suspend fun GroupCall.endScreenSharing() = api.endGroupCallScreenSharing(this.id)

  /**
   * Suspend function, which returns information about a group call.
   *
   *
   * @return [TdApi.GroupCall] Describes a group call.
   */
  suspend fun GroupCall.get() = api.getGroupCall(this.id)

  /**
   * Suspend function, which returns invite link to a video chat in a public chat.
   *
   * @param canSelfUnmute Pass true if the invite link needs to contain an invite hash, passing
   * which to joinVideoChat would allow the invited user to unmute themselves. Requires
   * groupCall.canBeManaged right.
   *
   * @return [TdApi.HttpUrl] Contains an HTTP URL.
   */
  suspend fun GroupCall.getVideoChatInviteLink(canSelfUnmute: Boolean) =
      api.getVideoChatInviteLink(this.id, canSelfUnmute)

  /**
   * Suspend function, which returns a file with a segment of a video chat stream in a modified OGG
   * format for audio or MPEG-4 format for video.
   *
   * @param timeOffset Point in time when the stream segment begins; Unix timestamp in milliseconds.
   *  
   * @param scale Segment duration scale; 0-1. Segment's duration is 1000/(2**scale) milliseconds.  
   * @param channelId Identifier of an audio/video channel to get as received from tgcalls.  
   * @param videoQuality Video quality as received from tgcalls; pass null to get the worst
   * available quality.
   *
   * @return [TdApi.Data] Contains some binary data.
   */
  suspend fun GroupCall.getVideoChatStreamSegment(
    timeOffset: Long,
    scale: Int,
    channelId: Int,
    videoQuality: GroupCallVideoQuality?
  ) = api.getVideoChatStreamSegment(this.id, timeOffset, scale, channelId, videoQuality)

  /**
   * Suspend function, which returns information about available video chat streams.
   *
   *
   * @return [TdApi.VideoChatStreams] Represents a list of video chat streams.
   */
  suspend fun GroupCall.getVideoChatStreams() = api.getVideoChatStreams(this.id)

  /**
   * Suspend function, which invites a user to an active group call; for group calls not bound to a
   * chat only. Sends a service message of the type messageGroupCall. The group call can have at most
   * getOption(&quot;group_call_participant_count_max&quot;) participants.
   *
   * @param userId User identifier.  
   * @param isVideo Pass true if the group call is a video call.
   *
   * @return [TdApi.InviteGroupCallParticipantResult] This class is an abstract base class.
   */
  suspend fun GroupCall.inviteParticipant(userId: Long, isVideo: Boolean) =
      api.inviteGroupCallParticipant(this.id, userId, isVideo)

  /**
   * Suspend function, which invites users to an active video chat. Sends a service message of the
   * type messageInviteVideoChatParticipants to the chat bound to the group call.
   *
   * @param userIds User identifiers. At most 10 users can be invited simultaneously.
   */
  suspend fun GroupCall.inviteVideoChatParticipants(userIds: LongArray?) =
      api.inviteVideoChatParticipants(this.id, userIds)

  /**
   * Suspend function, which joins an active video chat. Returns join response payload for tgcalls.
   *
   * @param participantId Identifier of a group call participant, which will be used to join the
   * call; pass null to join as self; video chats only.  
   * @param joinParameters Parameters to join the call.  
   * @param inviteHash Invite hash as received from internalLinkTypeVideoChat.
   *
   * @return [TdApi.Text] Contains some text.
   */
  suspend fun GroupCall.joinVideoChat(
    participantId: MessageSender?,
    joinParameters: GroupCallJoinParameters?,
    inviteHash: String?
  ) = api.joinVideoChat(this.id, participantId, joinParameters, inviteHash)

  /**
   * Suspend function, which leaves a group call.
   */
  suspend fun GroupCall.leave() = api.leaveGroupCall(this.id)

  /**
   * Suspend function, which loads more participants of a group call. The loaded participants will
   * be received through updates. Use the field groupCall.loadedAllParticipants to check whether all
   * participants have already been loaded.
   *
   * @param limit The maximum number of participants to load; up to 100.
   */
  suspend fun GroupCall.loadParticipants(limit: Int) = api.loadGroupCallParticipants(this.id, limit)

  /**
   * Suspend function, which revokes invite link for a group call. Requires groupCall.canBeManaged
   * right for video chats or groupCall.isOwned otherwise.
   */
  suspend fun GroupCall.revokeInviteLink() = api.revokeGroupCallInviteLink(this.id)

  /**
   * Suspend function, which sends a message to other participants of a group call. Requires
   * groupCall.canSendMessages right.
   *
   * @param text Text of the message to send;
   * 1-getOption(&quot;group_call_message_text_length_max&quot;) characters.
   */
  suspend fun GroupCall.sendMessage(text: FormattedText?) = api.sendGroupCallMessage(this.id, text)

  /**
   * Suspend function, which informs TDLib that speaking state of a participant of an active group
   * call has changed. Returns identifier of the participant if it is found.
   *
   * @param audioSource Group call participant's synchronization audio source identifier, or 0 for
   * the current user.  
   * @param isSpeaking Pass true if the user is speaking.
   *
   * @return [TdApi.MessageSender] This class is an abstract base class.
   */
  suspend fun GroupCall.setParticipantIsSpeaking(audioSource: Int, isSpeaking: Boolean) =
      api.setGroupCallParticipantIsSpeaking(this.id, audioSource, isSpeaking)

  /**
   * Suspend function, which changes volume level of a participant of an active group call. If the
   * current user can manage the group call or is the owner of the group call, then the participant's
   * volume level will be changed for all users with the default volume level.
   *
   * @param participantId Participant identifier.  
   * @param volumeLevel New participant's volume level; 1-20000 in hundreds of percents.
   */
  suspend fun GroupCall.setParticipantVolumeLevel(participantId: MessageSender?, volumeLevel: Int) =
      api.setGroupCallParticipantVolumeLevel(this.id, participantId, volumeLevel)

  /**
   * Suspend function, which sets title of a video chat; requires groupCall.canBeManaged right.
   *
   * @param title New group call title; 1-64 characters.
   */
  suspend fun GroupCall.setVideoChatTitle(title: String?) = api.setVideoChatTitle(this.id, title)

  /**
   * Suspend function, which starts recording of an active group call; for video chats only.
   * Requires groupCall.canBeManaged right.
   *
   * @param title Group call recording title; 0-64 characters.  
   * @param recordVideo Pass true to record a video file instead of an audio file.  
   * @param usePortraitOrientation Pass true to use portrait orientation for video instead of
   * landscape one.
   */
  suspend fun GroupCall.startRecording(
    title: String?,
    recordVideo: Boolean,
    usePortraitOrientation: Boolean
  ) = api.startGroupCallRecording(this.id, title, recordVideo, usePortraitOrientation)

  /**
   * Suspend function, which starts screen sharing in a joined group call. Returns join response
   * payload for tgcalls.
   *
   * @param audioSourceId Screen sharing audio channel synchronization source identifier; received
   * from tgcalls.  
   * @param payload Group call join payload; received from tgcalls.
   *
   * @return [TdApi.Text] Contains some text.
   */
  suspend fun GroupCall.startScreenSharing(audioSourceId: Int, payload: String?) =
      api.startGroupCallScreenSharing(this.id, audioSourceId, payload)

  /**
   * Suspend function, which starts a scheduled video chat.
   */
  suspend fun GroupCall.startScheduledVideoChat() = api.startScheduledVideoChat(this.id)

  /**
   * Suspend function, which toggles whether participants of a group call can send messages there.
   * Requires groupCall.canToggleCanSendMessages right.
   *
   * @param canSendMessages New value of the canSendMessages setting.
   */
  suspend fun GroupCall.toggleCanSendMessages(canSendMessages: Boolean) =
      api.toggleGroupCallCanSendMessages(this.id, canSendMessages)

  /**
   * Suspend function, which toggles whether current user's video is enabled.
   *
   * @param isMyVideoEnabled Pass true if the current user's video is enabled.
   */
  suspend fun GroupCall.toggleIsMyVideoEnabled(isMyVideoEnabled: Boolean) =
      api.toggleGroupCallIsMyVideoEnabled(this.id, isMyVideoEnabled)

  /**
   * Suspend function, which toggles whether current user's video is paused.
   *
   * @param isMyVideoPaused Pass true if the current user's video is paused.
   */
  suspend fun GroupCall.toggleIsMyVideoPaused(isMyVideoPaused: Boolean) =
      api.toggleGroupCallIsMyVideoPaused(this.id, isMyVideoPaused)

  /**
   * Suspend function, which toggles whether a group call participant hand is rased; for video chats
   * only.
   *
   * @param participantId Participant identifier.  
   * @param isHandRaised Pass true if the user's hand needs to be raised. Only self hand can be
   * raised. Requires groupCall.canBeManaged right to lower other's hand.
   */
  suspend fun GroupCall.toggleParticipantIsHandRaised(participantId: MessageSender?,
      isHandRaised: Boolean) = api.toggleGroupCallParticipantIsHandRaised(this.id, participantId,
      isHandRaised)

  /**
   * Suspend function, which toggles whether a participant of an active group call is muted,
   * unmuted, or allowed to unmute themselves.
   *
   * @param participantId Participant identifier.  
   * @param isMuted Pass true to mute the user; pass false to unmute them.
   */
  suspend fun GroupCall.toggleParticipantIsMuted(participantId: MessageSender?, isMuted: Boolean) =
      api.toggleGroupCallParticipantIsMuted(this.id, participantId, isMuted)

  /**
   * Suspend function, which pauses or unpauses screen sharing in a joined group call.
   *
   * @param isPaused Pass true to pause screen sharing; pass false to unpause it.
   */
  suspend fun GroupCall.toggleScreenSharingIsPaused(isPaused: Boolean) =
      api.toggleGroupCallScreenSharingIsPaused(this.id, isPaused)

  /**
   * Suspend function, which toggles whether the current user will receive a notification when the
   * video chat starts; for scheduled video chats only.
   *
   * @param enabledStartNotification New value of the enabledStartNotification setting.
   */
  suspend fun GroupCall.toggleVideoChatEnabledStartNotification(enabledStartNotification: Boolean) =
      api.toggleVideoChatEnabledStartNotification(this.id, enabledStartNotification)

  /**
   * Suspend function, which toggles whether new participants of a video chat can be unmuted only by
   * administrators of the video chat. Requires groupCall.canToggleMuteNewParticipants right.
   *
   * @param muteNewParticipants New value of the muteNewParticipants setting.
   */
  suspend fun GroupCall.toggleVideoChatMuteNewParticipants(muteNewParticipants: Boolean) =
      api.toggleVideoChatMuteNewParticipants(this.id, muteNewParticipants)
}
