//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.coroutines

import kotlin.Int
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.td.libcore.telegram.TdApi

/**
 * Suspend function, which adds an audio file to the beginning of the profile audio files of the
 * current user.
 *
 * @param fileId Identifier of the audio file to be added. The file must have been uploaded to the
 * server.
 */
suspend fun TelegramFlow.addProfileAudio(fileId: Int) =
    this.sendFunctionLaunch(TdApi.AddProfileAudio(fileId))

/**
 * Suspend function, which checks whether a file is in the profile audio files of the current user.
 * Returns a 404 error if it isn't.
 *
 * @param fileId Identifier of the audio file to check.
 */
suspend fun TelegramFlow.isProfileAudio(fileId: Int) =
    this.sendFunctionLaunch(TdApi.IsProfileAudio(fileId))

/**
 * Suspend function, which removes an audio file from the profile audio files of the current user.
 *
 * @param fileId Identifier of the audio file to be removed.
 */
suspend fun TelegramFlow.removeProfileAudio(fileId: Int) =
    this.sendFunctionLaunch(TdApi.RemoveProfileAudio(fileId))

/**
 * Suspend function, which changes position of an audio file in the profile audio files of the
 * current user.
 *
 * @param fileId Identifier of the file from profile audio files, which position will be changed.  
 * @param afterFileId Identifier of the file from profile audio files after which the file will be
 * positioned; pass 0 to move the file to the beginning of the list.
 */
suspend fun TelegramFlow.setProfileAudioPosition(fileId: Int, afterFileId: Int) =
    this.sendFunctionLaunch(TdApi.SetProfileAudioPosition(fileId, afterFileId))
