//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.coroutines

import kotlin.Long
import kotlin.String
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.tdlib.TdApi
import org.drinkless.tdlib.TdApi.Text

/**
 * Suspend function, which returns the text shown in the chat with a bot if the chat is empty in the
 * given language. Can be called only if userTypeBot.canBeEdited == true.
 *
 * @param botUserId Identifier of the target bot.  
 * @param languageCode A two-letter ISO 639-1 language code or an empty string.
 *
 * @return [Text] Contains some text.
 */
suspend fun TelegramFlow.getBotInfoDescription(botUserId: Long, languageCode: String?): Text =
    this.sendFunctionAsync(TdApi.GetBotInfoDescription(botUserId, languageCode))

/**
 * Suspend function, which returns the text shown on a bot's profile page and sent together with the
 * link when users share the bot in the given language. Can be called only if userTypeBot.canBeEdited
 * == true.
 *
 * @param botUserId Identifier of the target bot.  
 * @param languageCode A two-letter ISO 639-1 language code or an empty string.
 *
 * @return [Text] Contains some text.
 */
suspend fun TelegramFlow.getBotInfoShortDescription(botUserId: Long, languageCode: String?): Text =
    this.sendFunctionAsync(TdApi.GetBotInfoShortDescription(botUserId, languageCode))

/**
 * Suspend function, which sets the text shown in the chat with a bot if the chat is empty. Can be
 * called only if userTypeBot.canBeEdited == true.
 *
 * @param botUserId Identifier of the target bot.  
 * @param languageCode A two-letter ISO 639-1 language code. If empty, the description will be shown
 * to all users for whose languages there is no dedicated description.  
 * @param description New bot's description on the specified language.
 */
suspend fun TelegramFlow.setBotInfoDescription(
  botUserId: Long,
  languageCode: String?,
  description: String?
) = this.sendFunctionLaunch(TdApi.SetBotInfoDescription(botUserId, languageCode, description))

/**
 * Suspend function, which sets the text shown on a bot's profile page and sent together with the
 * link when users share the bot. Can be called only if userTypeBot.canBeEdited == true.
 *
 * @param botUserId Identifier of the target bot.  
 * @param languageCode A two-letter ISO 639-1 language code. If empty, the short description will be
 * shown to all users for whose languages there is no dedicated description.  
 * @param shortDescription New bot's short description on the specified language.
 */
suspend fun TelegramFlow.setBotInfoShortDescription(
  botUserId: Long,
  languageCode: String?,
  shortDescription: String?
) = this.sendFunctionLaunch(TdApi.SetBotInfoShortDescription(botUserId, languageCode,
    shortDescription))
