//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.coroutines

import kotlin.Array
import kotlin.IntArray
import kotlin.Long
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.tdlib.TdApi
import org.drinkless.tdlib.TdApi.InputChecklistTask

/**
 * Suspend function, which adds tasks to a checklist in a message.
 *
 * @param chatId Identifier of the chat with the message.  
 * @param messageId Identifier of the message containing the checklist. Use
 * messageProperties.canAddTasks to check whether the tasks can be added.  
 * @param tasks List of added tasks.
 */
suspend fun TelegramFlow.addChecklistTasks(
  chatId: Long,
  messageId: Long,
  tasks: Array<InputChecklistTask>?
) = this.sendFunctionLaunch(TdApi.AddChecklistTasks(chatId, messageId, tasks))

/**
 * Suspend function, which adds tasks of a checklist in a message as done or not done.
 *
 * @param chatId Identifier of the chat with the message.  
 * @param messageId Identifier of the message containing the checklist. Use
 * messageProperties.canMarkTasksAsDone to check whether the tasks can be marked as done or not done.  
 * @param markedAsDoneTaskIds Identifiers of tasks that were marked as done.  
 * @param markedAsNotDoneTaskIds Identifiers of tasks that were marked as not done.
 */
suspend fun TelegramFlow.markChecklistTasksAsDone(
  chatId: Long,
  messageId: Long,
  markedAsDoneTaskIds: IntArray?,
  markedAsNotDoneTaskIds: IntArray?
) = this.sendFunctionLaunch(TdApi.MarkChecklistTasksAsDone(chatId, messageId, markedAsDoneTaskIds,
    markedAsNotDoneTaskIds))
