//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.coroutines

import kotlin.Boolean
import kotlin.Int
import kotlin.IntArray
import kotlin.Long
import kotlin.String
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.td.libcore.telegram.TdApi
import org.drinkless.td.libcore.telegram.TdApi.ChatNotificationSettings
import org.drinkless.td.libcore.telegram.TdApi.ForumTopic
import org.drinkless.td.libcore.telegram.TdApi.ForumTopicIcon
import org.drinkless.td.libcore.telegram.TdApi.ForumTopicInfo
import org.drinkless.td.libcore.telegram.TdApi.ForumTopics
import org.drinkless.td.libcore.telegram.TdApi.MessageLink
import org.drinkless.td.libcore.telegram.TdApi.Messages
import org.drinkless.td.libcore.telegram.TdApi.Stickers

/**
 * Suspend function, which creates a topic in a forum supergroup chat or a chat with a bot with
 * topics; requires canManageTopics administrator or canCreateTopics member right in the supergroup.
 *
 * @param chatId Identifier of the chat.  
 * @param name Name of the topic; 1-128 characters.  
 * @param isNameImplicit Pass true if the name of the topic wasn't entered explicitly; for chats
 * with bots only.  
 * @param icon Icon of the topic. Icon color must be one of 0x6FB9F0, 0xFFD67E, 0xCB86DB, 0x8EEE98,
 * 0xFF93B2, or 0xFB6F5F. Telegram Premium users can use any custom emoji as topic icon, other users
 * can use only a custom emoji returned by getForumTopicDefaultIcons.
 *
 * @return [ForumTopicInfo] Contains basic information about a forum topic.
 */
suspend fun TelegramFlow.createForumTopic(
  chatId: Long,
  name: String?,
  isNameImplicit: Boolean,
  icon: ForumTopicIcon?
): ForumTopicInfo = this.sendFunctionAsync(TdApi.CreateForumTopic(chatId, name, isNameImplicit,
    icon))

/**
 * Suspend function, which deletes all messages from a topic in a forum supergroup chat or a chat
 * with a bot with topics; requires canDeleteMessages administrator right in the supergroup unless the
 * user is creator of the topic, the topic has no messages from other users and has at most 11
 * messages.
 *
 * @param chatId Identifier of the chat.  
 * @param forumTopicId Forum topic identifier.
 */
suspend fun TelegramFlow.deleteForumTopic(chatId: Long, forumTopicId: Int) =
    this.sendFunctionLaunch(TdApi.DeleteForumTopic(chatId, forumTopicId))

/**
 * Suspend function, which edits title and icon of a topic in a forum supergroup chat or a chat with
 * a bot with topics; for supergroup chats requires canManageTopics administrator right unless the user
 * is creator of the topic.
 *
 * @param chatId Identifier of the chat.  
 * @param forumTopicId Forum topic identifier.  
 * @param name New name of the topic; 0-128 characters. If empty, the previous topic name is kept.  
 * @param editIconCustomEmoji Pass true to edit the icon of the topic. Icon of the General topic
 * can't be edited.  
 * @param iconCustomEmojiId Identifier of the new custom emoji for topic icon; pass 0 to remove the
 * custom emoji. Ignored if editIconCustomEmoji is false. Telegram Premium users can use any custom
 * emoji, other users can use only a custom emoji returned by getForumTopicDefaultIcons.
 */
suspend fun TelegramFlow.editForumTopic(
  chatId: Long,
  forumTopicId: Int,
  name: String?,
  editIconCustomEmoji: Boolean,
  iconCustomEmojiId: Long
) = this.sendFunctionLaunch(TdApi.EditForumTopic(chatId, forumTopicId, name, editIconCustomEmoji,
    iconCustomEmojiId))

/**
 * Suspend function, which returns information about a topic in a forum supergroup chat or a chat
 * with a bot with topics.
 *
 * @param chatId Identifier of the chat.  
 * @param forumTopicId Forum topic identifier.
 *
 * @return [ForumTopic] Describes a forum topic.
 */
suspend fun TelegramFlow.getForumTopic(chatId: Long, forumTopicId: Int): ForumTopic =
    this.sendFunctionAsync(TdApi.GetForumTopic(chatId, forumTopicId))

/**
 * Suspend function, which returns the list of custom emoji, which can be used as forum topic icon
 * by all users.
 *
 * @return [Stickers] Represents a list of stickers.
 */
suspend fun TelegramFlow.getForumTopicDefaultIcons(): Stickers =
    this.sendFunctionAsync(TdApi.GetForumTopicDefaultIcons())

/**
 * Suspend function, which returns messages in a topic in a forum supergroup chat or a chat with a
 * bot with topics. The messages are returned in reverse chronological order (i.e., in order of
 * decreasing messageId). For optimal performance, the number of returned messages is chosen by TDLib.
 *
 * @param chatId Chat identifier.  
 * @param forumTopicId Forum topic identifier.  
 * @param fromMessageId Identifier of the message starting from which history must be fetched; use 0
 * to get results from the last message.  
 * @param offset Specify 0 to get results from exactly the message fromMessageId or a negative
 * number from -99 to -1 to get additionally -offset newer messages.  
 * @param limit The maximum number of messages to be returned; must be positive and can't be greater
 * than 100. If the offset is negative, then the limit must be greater than or equal to -offset. For
 * optimal performance, the number of returned messages is chosen by TDLib and can be smaller than the
 * specified limit.
 *
 * @return [Messages] Contains a list of messages.
 */
suspend fun TelegramFlow.getForumTopicHistory(
  chatId: Long,
  forumTopicId: Int,
  fromMessageId: Long,
  offset: Int,
  limit: Int
): Messages = this.sendFunctionAsync(TdApi.GetForumTopicHistory(chatId, forumTopicId, fromMessageId,
    offset, limit))

/**
 * Suspend function, which returns an HTTPS link to a topic in a forum supergroup chat. This is an
 * offline method.
 *
 * @param chatId Identifier of the chat.  
 * @param forumTopicId Forum topic identifier.
 *
 * @return [MessageLink] Contains an HTTPS link to a message in a supergroup or channel, or a forum
 * topic.
 */
suspend fun TelegramFlow.getForumTopicLink(chatId: Long, forumTopicId: Int): MessageLink =
    this.sendFunctionAsync(TdApi.GetForumTopicLink(chatId, forumTopicId))

/**
 * Suspend function, which returns found forum topics in a forum supergroup chat or a chat with a
 * bot with topics. This is a temporary method for getting information about topic list from the
 * server.
 *
 * @param chatId Identifier of the chat.  
 * @param query Query to search for in the forum topic's name.  
 * @param offsetDate The date starting from which the results need to be fetched. Use 0 or any date
 * in the future to get results from the last topic.  
 * @param offsetMessageId The message identifier of the last message in the last found topic, or 0
 * for the first request.  
 * @param offsetForumTopicId The forum topic identifier of the last found topic, or 0 for the first
 * request.  
 * @param limit The maximum number of forum topics to be returned; up to 100. For optimal
 * performance, the number of returned forum topics is chosen by TDLib and can be smaller than the
 * specified limit.
 *
 * @return [ForumTopics] Describes a list of forum topics.
 */
suspend fun TelegramFlow.getForumTopics(
  chatId: Long,
  query: String?,
  offsetDate: Int,
  offsetMessageId: Long,
  offsetForumTopicId: Int,
  limit: Int
): ForumTopics = this.sendFunctionAsync(TdApi.GetForumTopics(chatId, query, offsetDate,
    offsetMessageId, offsetForumTopicId, limit))

/**
 * Suspend function, which marks all mentions in a topic in a forum supergroup chat as read.
 *
 * @param chatId Chat identifier.  
 * @param forumTopicId Forum topic identifier in which mentions are marked as read.
 */
suspend fun TelegramFlow.readAllForumTopicMentions(chatId: Long, forumTopicId: Int) =
    this.sendFunctionLaunch(TdApi.ReadAllForumTopicMentions(chatId, forumTopicId))

/**
 * Suspend function, which marks all reactions in a topic in a forum supergroup chat or a chat with
 * a bot with topics as read.
 *
 * @param chatId Chat identifier.  
 * @param forumTopicId Forum topic identifier in which reactions are marked as read.
 */
suspend fun TelegramFlow.readAllForumTopicReactions(chatId: Long, forumTopicId: Int) =
    this.sendFunctionLaunch(TdApi.ReadAllForumTopicReactions(chatId, forumTopicId))

/**
 * Suspend function, which changes the notification settings of a forum topic in a forum supergroup
 * chat or a chat with a bot with topics.
 *
 * @param chatId Chat identifier.  
 * @param forumTopicId Forum topic identifier.  
 * @param notificationSettings New notification settings for the forum topic. If the topic is muted
 * for more than 366 days, it is considered to be muted forever.
 */
suspend fun TelegramFlow.setForumTopicNotificationSettings(
  chatId: Long,
  forumTopicId: Int,
  notificationSettings: ChatNotificationSettings?
) = this.sendFunctionLaunch(TdApi.SetForumTopicNotificationSettings(chatId, forumTopicId,
    notificationSettings))

/**
 * Suspend function, which changes the order of pinned topics in a forum supergroup chat or a chat
 * with a bot with topics; requires canManageTopics administrator right in the supergroup.
 *
 * @param chatId Chat identifier.  
 * @param forumTopicIds The new list of identifiers of the pinned forum topics.
 */
suspend fun TelegramFlow.setPinnedForumTopics(chatId: Long, forumTopicIds: IntArray?) =
    this.sendFunctionLaunch(TdApi.SetPinnedForumTopics(chatId, forumTopicIds))

/**
 * Suspend function, which toggles whether a topic is closed in a forum supergroup chat; requires
 * canManageTopics administrator right in the supergroup unless the user is creator of the topic.
 *
 * @param chatId Identifier of the chat.  
 * @param forumTopicId Forum topic identifier.  
 * @param isClosed Pass true to close the topic; pass false to reopen it.
 */
suspend fun TelegramFlow.toggleForumTopicIsClosed(
  chatId: Long,
  forumTopicId: Int,
  isClosed: Boolean
) = this.sendFunctionLaunch(TdApi.ToggleForumTopicIsClosed(chatId, forumTopicId, isClosed))

/**
 * Suspend function, which changes the pinned state of a topic in a forum supergroup chat or a chat
 * with a bot with topics; requires canManageTopics administrator right in the supergroup. There can be
 * up to getOption(&quot;pinned_forum_topic_count_max&quot;) pinned forum topics.
 *
 * @param chatId Chat identifier.  
 * @param forumTopicId Forum topic identifier.  
 * @param isPinned Pass true to pin the topic; pass false to unpin it.
 */
suspend fun TelegramFlow.toggleForumTopicIsPinned(
  chatId: Long,
  forumTopicId: Int,
  isPinned: Boolean
) = this.sendFunctionLaunch(TdApi.ToggleForumTopicIsPinned(chatId, forumTopicId, isPinned))

/**
 * Suspend function, which toggles whether a General topic is hidden in a forum supergroup chat;
 * requires canManageTopics administrator right in the supergroup.
 *
 * @param chatId Identifier of the chat.  
 * @param isHidden Pass true to hide and close the General topic; pass false to unhide it.
 */
suspend fun TelegramFlow.toggleGeneralForumTopicIsHidden(chatId: Long, isHidden: Boolean) =
    this.sendFunctionLaunch(TdApi.ToggleGeneralForumTopicIsHidden(chatId, isHidden))
