//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.coroutines

import kotlin.Array
import kotlin.Boolean
import kotlin.Int
import kotlin.IntArray
import kotlin.Long
import kotlin.String
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.td.libcore.telegram.TdApi
import org.drinkless.td.libcore.telegram.TdApi.AvailableGifts
import org.drinkless.td.libcore.telegram.TdApi.CanSendGiftResult
import org.drinkless.td.libcore.telegram.TdApi.FormattedText
import org.drinkless.td.libcore.telegram.TdApi.GiftCollection
import org.drinkless.td.libcore.telegram.TdApi.GiftCollections
import org.drinkless.td.libcore.telegram.TdApi.GiftForResaleOrder
import org.drinkless.td.libcore.telegram.TdApi.GiftResalePrice
import org.drinkless.td.libcore.telegram.TdApi.GiftResaleResult
import org.drinkless.td.libcore.telegram.TdApi.GiftSettings
import org.drinkless.td.libcore.telegram.TdApi.GiftUpgradePreview
import org.drinkless.td.libcore.telegram.TdApi.GiftsForResale
import org.drinkless.td.libcore.telegram.TdApi.HttpUrl
import org.drinkless.td.libcore.telegram.TdApi.MessageSender
import org.drinkless.td.libcore.telegram.TdApi.PremiumGiftCodeInfo
import org.drinkless.td.libcore.telegram.TdApi.ReceivedGift
import org.drinkless.td.libcore.telegram.TdApi.ReceivedGifts
import org.drinkless.td.libcore.telegram.TdApi.UpgradeGiftResult
import org.drinkless.td.libcore.telegram.TdApi.UpgradedGift
import org.drinkless.td.libcore.telegram.TdApi.UpgradedGiftAttributeId
import org.drinkless.td.libcore.telegram.TdApi.UpgradedGiftValueInfo

/**
 * Suspend function, which adds gifts to the beginning of a previously created collection. If the
 * collection is owned by a channel chat, then requires canPostMessages administrator right in the
 * channel chat. Returns the changed collection.
 *
 * @param ownerId Identifier of the user or the channel chat that owns the collection.  
 * @param collectionId Identifier of the gift collection.  
 * @param receivedGiftIds Identifier of the gifts to add to the collection;
 * 1-getOption(&quot;gift_collection_gift_count_max&quot;) identifiers. If after addition the
 * collection has more than getOption(&quot;gift_collection_gift_count_max&quot;) gifts, then the last
 * one are removed from the collection.
 *
 * @return [GiftCollection] Describes collection of gifts.
 */
suspend fun TelegramFlow.addGiftCollectionGifts(
  ownerId: MessageSender?,
  collectionId: Int,
  receivedGiftIds: Array<String>?
): GiftCollection = this.sendFunctionAsync(TdApi.AddGiftCollectionGifts(ownerId, collectionId,
    receivedGiftIds))

/**
 * Suspend function, which applies a Telegram Premium gift code.
 *
 * @param code The code to apply.
 */
suspend fun TelegramFlow.applyPremiumGiftCode(code: String?) =
    this.sendFunctionLaunch(TdApi.ApplyPremiumGiftCode(code))

/**
 * Suspend function, which pays for upgrade of a regular gift that is owned by another user or
 * channel chat.
 *
 * @param ownerId Identifier of the user or the channel chat that owns the gift.  
 * @param prepaidUpgradeHash Prepaid upgrade hash as received along with the gift.  
 * @param starCount The amount of Telegram Stars the user agreed to pay for the upgrade; must be
 * equal to gift.upgradeStarCount.
 */
suspend fun TelegramFlow.buyGiftUpgrade(
  ownerId: MessageSender?,
  prepaidUpgradeHash: String?,
  starCount: Long
) = this.sendFunctionLaunch(TdApi.BuyGiftUpgrade(ownerId, prepaidUpgradeHash, starCount))

/**
 * Suspend function, which checks whether a gift with nextSendDate in the future can be sent
 * already.
 *
 * @param giftId Identifier of the gift to send.
 *
 * @return [CanSendGiftResult] This class is an abstract base class.
 */
suspend fun TelegramFlow.canSendGift(giftId: Long): CanSendGiftResult =
    this.sendFunctionAsync(TdApi.CanSendGift(giftId))

/**
 * Suspend function, which return information about a Telegram Premium gift code.
 *
 * @param code The code to check.
 *
 * @return [PremiumGiftCodeInfo] Contains information about a Telegram Premium gift code.
 */
suspend fun TelegramFlow.checkPremiumGiftCode(code: String?): PremiumGiftCodeInfo =
    this.sendFunctionAsync(TdApi.CheckPremiumGiftCode(code))

/**
 * Suspend function, which creates a collection from gifts on the current user's or a channel's
 * profile page; requires canPostMessages administrator right in the channel chat. An owner can have up
 * to getOption(&quot;gift_collection_count_max&quot;) gift collections. The new collection will be
 * added to the end of the gift collection list of the owner. Returns the created collection.
 *
 * @param ownerId Identifier of the user or the channel chat that received the gifts.  
 * @param name Name of the collection; 1-12 characters.  
 * @param receivedGiftIds Identifier of the gifts to add to the collection;
 * 0-getOption(&quot;gift_collection_gift_count_max&quot;) identifiers.
 *
 * @return [GiftCollection] Describes collection of gifts.
 */
suspend fun TelegramFlow.createGiftCollection(
  ownerId: MessageSender?,
  name: String?,
  receivedGiftIds: Array<String>?
): GiftCollection = this.sendFunctionAsync(TdApi.CreateGiftCollection(ownerId, name,
    receivedGiftIds))

/**
 * Suspend function, which deletes a gift collection. If the collection is owned by a channel chat,
 * then requires canPostMessages administrator right in the channel chat.
 *
 * @param ownerId Identifier of the user or the channel chat that owns the collection.  
 * @param collectionId Identifier of the gift collection.
 */
suspend fun TelegramFlow.deleteGiftCollection(ownerId: MessageSender?, collectionId: Int) =
    this.sendFunctionLaunch(TdApi.DeleteGiftCollection(ownerId, collectionId))

/**
 * Suspend function, which drops original details for an upgraded gift.
 *
 * @param receivedGiftId Identifier of the gift.  
 * @param starCount The amount of Telegram Stars required to pay for the operation.
 */
suspend fun TelegramFlow.dropGiftOriginalDetails(receivedGiftId: String?, starCount: Long) =
    this.sendFunctionLaunch(TdApi.DropGiftOriginalDetails(receivedGiftId, starCount))

/**
 * Suspend function, which returns gifts that can be sent to other users and channel chats.
 *
 * @return [AvailableGifts] Contains a list of gifts that can be sent to another user or channel
 * chat.
 */
suspend fun TelegramFlow.getAvailableGifts(): AvailableGifts =
    this.sendFunctionAsync(TdApi.GetAvailableGifts())

/**
 * Suspend function, which returns collections of gifts owned by the given user or chat.
 *
 * @param ownerId Identifier of the user or the channel chat that received the gifts.
 *
 * @return [GiftCollections] Contains a list of gift collections.
 */
suspend fun TelegramFlow.getGiftCollections(ownerId: MessageSender?): GiftCollections =
    this.sendFunctionAsync(TdApi.GetGiftCollections(ownerId))

/**
 * Suspend function, which returns examples of possible upgraded gifts for a regular gift.
 *
 * @param giftId Identifier of the gift.
 *
 * @return [GiftUpgradePreview] Contains examples of possible upgraded gifts for the given regular
 * gift.
 */
suspend fun TelegramFlow.getGiftUpgradePreview(giftId: Long): GiftUpgradePreview =
    this.sendFunctionAsync(TdApi.GetGiftUpgradePreview(giftId))

/**
 * Suspend function, which returns information about a received gift.
 *
 * @param receivedGiftId Identifier of the gift.
 *
 * @return [ReceivedGift] Represents a gift received by a user or a chat.
 */
suspend fun TelegramFlow.getReceivedGift(receivedGiftId: String?): ReceivedGift =
    this.sendFunctionAsync(TdApi.GetReceivedGift(receivedGiftId))

/**
 * Suspend function, which returns gifts received by the given user or chat.
 *
 * @param businessConnectionId Unique identifier of business connection on behalf of which to send
 * the request; for bots only.  
 * @param ownerId Identifier of the gift receiver.  
 * @param collectionId Pass collection identifier to get gifts only from the specified collection;
 * pass 0 to get gifts regardless of collections.  
 * @param excludeUnsaved Pass true to exclude gifts that aren't saved to the chat's profile page.
 * Always true for gifts received by other users and channel chats without canPostMessages
 * administrator right.  
 * @param excludeSaved Pass true to exclude gifts that are saved to the chat's profile page. Always
 * false for gifts received by other users and channel chats without canPostMessages administrator
 * right.  
 * @param excludeUnlimited Pass true to exclude gifts that can be purchased unlimited number of
 * times.  
 * @param excludeUpgradable Pass true to exclude gifts that can be purchased limited number of times
 * and can be upgraded.  
 * @param excludeNonUpgradable Pass true to exclude gifts that can be purchased limited number of
 * times and can't be upgraded.  
 * @param excludeUpgraded Pass true to exclude upgraded gifts.  
 * @param excludeWithoutColors Pass true to exclude gifts that can't be used in
 * setUpgradedGiftColors.  
 * @param excludeHosted Pass true to exclude gifts that are just hosted and are not owned by the
 * owner.  
 * @param sortByPrice Pass true to sort results by gift price instead of send date.  
 * @param offset Offset of the first entry to return as received from the previous request; use
 * empty string to get the first chunk of results.  
 * @param limit The maximum number of gifts to be returned; must be positive and can't be greater
 * than 100. For optimal performance, the number of returned objects is chosen by TDLib and can be
 * smaller than the specified limit.
 *
 * @return [ReceivedGifts] Represents a list of gifts received by a user or a chat.
 */
suspend fun TelegramFlow.getReceivedGifts(
  businessConnectionId: String?,
  ownerId: MessageSender?,
  collectionId: Int,
  excludeUnsaved: Boolean,
  excludeSaved: Boolean,
  excludeUnlimited: Boolean,
  excludeUpgradable: Boolean,
  excludeNonUpgradable: Boolean,
  excludeUpgraded: Boolean,
  excludeWithoutColors: Boolean,
  excludeHosted: Boolean,
  sortByPrice: Boolean,
  offset: String?,
  limit: Int
): ReceivedGifts = this.sendFunctionAsync(TdApi.GetReceivedGifts(businessConnectionId, ownerId,
    collectionId, excludeUnsaved, excludeSaved, excludeUnlimited, excludeUpgradable,
    excludeNonUpgradable, excludeUpgraded, excludeWithoutColors, excludeHosted, sortByPrice, offset,
    limit))

/**
 * Suspend function, which returns information about an upgraded gift by its name.
 *
 * @param name Unique name of the upgraded gift.
 *
 * @return [UpgradedGift] Describes an upgraded gift that can be transferred to another owner or
 * transferred to the TON blockchain as an NFT.
 */
suspend fun TelegramFlow.getUpgradedGift(name: String?): UpgradedGift =
    this.sendFunctionAsync(TdApi.GetUpgradedGift(name))

/**
 * Suspend function, which returns information about value of an upgraded gift by its name.
 *
 * @param name Unique name of the upgraded gift.
 *
 * @return [UpgradedGiftValueInfo] Contains information about value of an upgraded gift.
 */
suspend fun TelegramFlow.getUpgradedGiftValueInfo(name: String?): UpgradedGiftValueInfo =
    this.sendFunctionAsync(TdApi.GetUpgradedGiftValueInfo(name))

/**
 * Suspend function, which returns a URL for upgraded gift withdrawal in the TON blockchain as an
 * NFT; requires owner privileges for gifts owned by a chat.
 *
 * @param receivedGiftId Identifier of the gift.  
 * @param password The 2-step verification password of the current user.
 *
 * @return [HttpUrl] Contains an HTTP URL.
 */
suspend fun TelegramFlow.getUpgradedGiftWithdrawalUrl(receivedGiftId: String?, password: String?):
    HttpUrl = this.sendFunctionAsync(TdApi.GetUpgradedGiftWithdrawalUrl(receivedGiftId, password))

/**
 * Suspend function, which removes gifts from a collection. If the collection is owned by a channel
 * chat, then requires canPostMessages administrator right in the channel chat. Returns the changed
 * collection.
 *
 * @param ownerId Identifier of the user or the channel chat that owns the collection.  
 * @param collectionId Identifier of the gift collection.  
 * @param receivedGiftIds Identifier of the gifts to remove from the collection.
 *
 * @return [GiftCollection] Describes collection of gifts.
 */
suspend fun TelegramFlow.removeGiftCollectionGifts(
  ownerId: MessageSender?,
  collectionId: Int,
  receivedGiftIds: Array<String>?
): GiftCollection = this.sendFunctionAsync(TdApi.RemoveGiftCollectionGifts(ownerId, collectionId,
    receivedGiftIds))

/**
 * Suspend function, which changes order of gifts in a collection. If the collection is owned by a
 * channel chat, then requires canPostMessages administrator right in the channel chat. Returns the
 * changed collection.
 *
 * @param ownerId Identifier of the user or the channel chat that owns the collection.  
 * @param collectionId Identifier of the gift collection.  
 * @param receivedGiftIds Identifier of the gifts to move to the beginning of the collection. All
 * other gifts are placed in the current order after the specified gifts.
 *
 * @return [GiftCollection] Describes collection of gifts.
 */
suspend fun TelegramFlow.reorderGiftCollectionGifts(
  ownerId: MessageSender?,
  collectionId: Int,
  receivedGiftIds: Array<String>?
): GiftCollection = this.sendFunctionAsync(TdApi.ReorderGiftCollectionGifts(ownerId, collectionId,
    receivedGiftIds))

/**
 * Suspend function, which changes order of gift collections. If the collections are owned by a
 * channel chat, then requires canPostMessages administrator right in the channel chat.
 *
 * @param ownerId Identifier of the user or the channel chat that owns the collection.  
 * @param collectionIds New order of gift collections.
 */
suspend fun TelegramFlow.reorderGiftCollections(ownerId: MessageSender?, collectionIds: IntArray?) =
    this.sendFunctionLaunch(TdApi.ReorderGiftCollections(ownerId, collectionIds))

/**
 * Suspend function, which returns upgraded gifts that can be bought from other owners using
 * sendResoldGift.
 *
 * @param giftId Identifier of the regular gift that was upgraded to a unique gift.  
 * @param order Order in which the results will be sorted.  
 * @param attributes Attributes used to filter received gifts. If multiple attributes of the same
 * type are specified, then all of them are allowed. If none attributes of specific type are specified,
 * then all values for this attribute type are allowed.  
 * @param offset Offset of the first entry to return as received from the previous request with the
 * same order and attributes; use empty string to get the first chunk of results.  
 * @param limit The maximum number of gifts to return.
 *
 * @return [GiftsForResale] Describes gifts available for resale.
 */
suspend fun TelegramFlow.searchGiftsForResale(
  giftId: Long,
  order: GiftForResaleOrder?,
  attributes: Array<UpgradedGiftAttributeId>?,
  offset: String?,
  limit: Int
): GiftsForResale = this.sendFunctionAsync(TdApi.SearchGiftsForResale(giftId, order, attributes,
    offset, limit))

/**
 * Suspend function, which sells a gift for Telegram Stars; requires owner privileges for gifts
 * owned by a chat.
 *
 * @param businessConnectionId Unique identifier of business connection on behalf of which to send
 * the request; for bots only.  
 * @param receivedGiftId Identifier of the gift.
 */
suspend fun TelegramFlow.sellGift(businessConnectionId: String?, receivedGiftId: String?) =
    this.sendFunctionLaunch(TdApi.SellGift(businessConnectionId, receivedGiftId))

/**
 * Suspend function, which sends a gift to another user or channel chat. May return an error with a
 * message &quot;STARGIFT_USAGE_LIMITED&quot; if the gift was sold out.
 *
 * @param giftId Identifier of the gift to send.  
 * @param ownerId Identifier of the user or the channel chat that will receive the gift; limited
 * gifts can't be sent to channel chats.  
 * @param text Text to show along with the gift; 0-getOption(&quot;gift_text_length_max&quot;)
 * characters. Only Bold, Italic, Underline, Strikethrough, Spoiler, and CustomEmoji entities are
 * allowed. Must be empty if the receiver enabled paid messages.  
 * @param isPrivate Pass true to show gift text and sender only to the gift receiver; otherwise,
 * everyone will be able to see them.  
 * @param payForUpgrade Pass true to additionally pay for the gift upgrade and allow the receiver to
 * upgrade it for free.
 */
suspend fun TelegramFlow.sendGift(
  giftId: Long,
  ownerId: MessageSender?,
  text: FormattedText?,
  isPrivate: Boolean,
  payForUpgrade: Boolean
) = this.sendFunctionLaunch(TdApi.SendGift(giftId, ownerId, text, isPrivate, payForUpgrade))

/**
 * Suspend function, which sends an upgraded gift that is available for resale to another user or
 * channel chat; gifts already owned by the current user must be transferred using transferGift and
 * can't be passed to the method.
 *
 * @param giftName Name of the upgraded gift to send.  
 * @param ownerId Identifier of the user or the channel chat that will receive the gift.  
 * @param price The price that the user agreed to pay for the gift.
 *
 * @return [GiftResaleResult] This class is an abstract base class.
 */
suspend fun TelegramFlow.sendResoldGift(
  giftName: String?,
  ownerId: MessageSender?,
  price: GiftResalePrice?
): GiftResaleResult = this.sendFunctionAsync(TdApi.SendResoldGift(giftName, ownerId, price))

/**
 * Suspend function, which changes name of a gift collection. If the collection is owned by a
 * channel chat, then requires canPostMessages administrator right in the channel chat. Returns the
 * changed collection.
 *
 * @param ownerId Identifier of the user or the channel chat that owns the collection.  
 * @param collectionId Identifier of the gift collection.  
 * @param name New name of the collection; 1-12 characters.
 *
 * @return [GiftCollection] Describes collection of gifts.
 */
suspend fun TelegramFlow.setGiftCollectionName(
  ownerId: MessageSender?,
  collectionId: Int,
  name: String?
): GiftCollection = this.sendFunctionAsync(TdApi.SetGiftCollectionName(ownerId, collectionId, name))

/**
 * Suspend function, which changes resale price of a unique gift owned by the current user.
 *
 * @param receivedGiftId Identifier of the unique gift.  
 * @param price The new price for the unique gift; pass null to disallow gift resale. The current
 * user will receive getOption(&quot;gift_resale_star_earnings_per_mille&quot;) Telegram Stars for each
 * 1000 Telegram Stars paid for the gift if the gift price is in Telegram Stars or
 * getOption(&quot;gift_resale_ton_earnings_per_mille&quot;) Toncoins for each 1000 Toncoins paid for
 * the gift if the gift price is in Toncoins.
 */
suspend fun TelegramFlow.setGiftResalePrice(receivedGiftId: String?, price: GiftResalePrice?) =
    this.sendFunctionLaunch(TdApi.SetGiftResalePrice(receivedGiftId, price))

/**
 * Suspend function, which changes settings for gift receiving for the current user.
 *
 * @param settings The new settings.
 */
suspend fun TelegramFlow.setGiftSettings(settings: GiftSettings?) =
    this.sendFunctionLaunch(TdApi.SetGiftSettings(settings))

/**
 * Suspend function, which changes the list of pinned gifts on the current user's or the channel's
 * profile page; requires canPostMessages administrator right in the channel chat.
 *
 * @param ownerId Identifier of the user or the channel chat that received the gifts.  
 * @param receivedGiftIds New list of pinned gifts. All gifts must be upgraded and saved on the
 * profile page first. There can be up to getOption(&quot;pinned_gift_count_max&quot;) pinned gifts.
 */
suspend fun TelegramFlow.setPinnedGifts(ownerId: MessageSender?, receivedGiftIds: Array<String>?) =
    this.sendFunctionLaunch(TdApi.SetPinnedGifts(ownerId, receivedGiftIds))

/**
 * Suspend function, which changes color scheme for the current user based on an owned or a hosted
 * upgraded gift; for Telegram Premium users only.
 *
 * @param upgradedGiftColorsId Identifier of the upgradedGiftColors scheme to use.
 */
suspend fun TelegramFlow.setUpgradedGiftColors(upgradedGiftColorsId: Long) =
    this.sendFunctionLaunch(TdApi.SetUpgradedGiftColors(upgradedGiftColorsId))

/**
 * Suspend function, which toggles whether a gift is shown on the current user's or the channel's
 * profile page; requires canPostMessages administrator right in the channel chat.
 *
 * @param receivedGiftId Identifier of the gift.  
 * @param isSaved Pass true to display the gift on the user's or the channel's profile page; pass
 * false to remove it from the profile page.
 */
suspend fun TelegramFlow.toggleGiftIsSaved(receivedGiftId: String?, isSaved: Boolean) =
    this.sendFunctionLaunch(TdApi.ToggleGiftIsSaved(receivedGiftId, isSaved))

/**
 * Suspend function, which sends an upgraded gift to another user or channel chat.
 *
 * @param businessConnectionId Unique identifier of business connection on behalf of which to send
 * the request; for bots only.  
 * @param receivedGiftId Identifier of the gift.  
 * @param newOwnerId Identifier of the user or the channel chat that will receive the gift.  
 * @param starCount The amount of Telegram Stars required to pay for the transfer.
 */
suspend fun TelegramFlow.transferGift(
  businessConnectionId: String?,
  receivedGiftId: String?,
  newOwnerId: MessageSender?,
  starCount: Long
) = this.sendFunctionLaunch(TdApi.TransferGift(businessConnectionId, receivedGiftId, newOwnerId,
    starCount))

/**
 * Suspend function, which upgrades a regular gift.
 *
 * @param businessConnectionId Unique identifier of business connection on behalf of which to send
 * the request; for bots only.  
 * @param receivedGiftId Identifier of the gift.  
 * @param keepOriginalDetails Pass true to keep the original gift text, sender and receiver in the
 * upgraded gift.  
 * @param starCount The amount of Telegram Stars required to pay for the upgrade. It the gift has
 * prepaidUpgradeStarCount &gt; 0, then pass 0, otherwise, pass gift.upgradeStarCount.
 *
 * @return [UpgradeGiftResult] Contains result of gift upgrading.
 */
suspend fun TelegramFlow.upgradeGift(
  businessConnectionId: String?,
  receivedGiftId: String?,
  keepOriginalDetails: Boolean,
  starCount: Long
): UpgradeGiftResult = this.sendFunctionAsync(TdApi.UpgradeGift(businessConnectionId,
    receivedGiftId, keepOriginalDetails, starCount))
