//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.coroutines

import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.td.libcore.telegram.TdApi
import org.drinkless.tdlib.TdApi.InputFile
import org.drinkless.tdlib.TdApi.NotificationSettingsScope
import org.drinkless.tdlib.TdApi.NotificationSound
import org.drinkless.tdlib.TdApi.NotificationSounds
import org.drinkless.tdlib.TdApi.ReactionNotificationSettings
import org.drinkless.tdlib.TdApi.ScopeNotificationSettings

/**
 * Suspend function, which adds a new notification sound to the list of saved notification sounds.
 * The new notification sound is added to the top of the list. If it is already in the list, its
 * position isn't changed.
 *
 * @param sound Notification sound file to add.
 *
 * @return [NotificationSound] Describes a notification sound in MP3 format.
 */
suspend fun TelegramFlow.addSavedNotificationSound(sound: InputFile?): NotificationSound =
    this.sendFunctionAsync(TdApi.AddSavedNotificationSound(sound))

/**
 * Suspend function, which returns saved notification sound by its identifier. Returns a 404 error
 * if there is no saved notification sound with the specified identifier.
 *
 * @param notificationSoundId Identifier of the notification sound.
 *
 * @return [NotificationSounds] Contains a list of notification sounds.
 */
suspend fun TelegramFlow.getSavedNotificationSound(notificationSoundId: Long): NotificationSounds =
    this.sendFunctionAsync(TdApi.GetSavedNotificationSound(notificationSoundId))

/**
 * Suspend function, which returns the list of saved notification sounds. If a sound isn't in the
 * list, then default sound needs to be used.
 *
 * @return [NotificationSounds] Contains a list of notification sounds.
 */
suspend fun TelegramFlow.getSavedNotificationSounds(): NotificationSounds =
    this.sendFunctionAsync(TdApi.GetSavedNotificationSounds())

/**
 * Suspend function, which returns the notification settings for chats of a given type.
 *
 * @param scope Types of chats for which to return the notification settings information.
 *
 * @return [ScopeNotificationSettings] Contains information about notification settings for several
 * chats.
 */
suspend fun TelegramFlow.getScopeNotificationSettings(scope: NotificationSettingsScope?):
    ScopeNotificationSettings = this.sendFunctionAsync(TdApi.GetScopeNotificationSettings(scope))

/**
 * Suspend function, which handles a push notification. Returns error with code 406 if the push
 * notification is not supported and connection to the server is required to fetch new data. Can be
 * called before authorization.
 *
 * @param payload JSON-encoded push notification payload with all fields sent by the server, and
 * &quot;google.sentTime&quot; and &quot;google.notification.sound&quot; fields added.
 */
suspend fun TelegramFlow.processPushNotification(payload: String?) =
    this.sendFunctionLaunch(TdApi.ProcessPushNotification(payload))

/**
 * Suspend function, which removes an active notification from notification list. Needs to be called
 * only if the notification is removed by the current user.
 *
 * @param notificationGroupId Identifier of notification group to which the notification belongs.  
 * @param notificationId Identifier of removed notification.
 */
suspend fun TelegramFlow.removeNotification(notificationGroupId: Int, notificationId: Int) =
    this.sendFunctionLaunch(TdApi.RemoveNotification(notificationGroupId, notificationId))

/**
 * Suspend function, which removes a group of active notifications. Needs to be called only if the
 * notification group is removed by the current user.
 *
 * @param notificationGroupId Notification group identifier.  
 * @param maxNotificationId The maximum identifier of removed notifications.
 */
suspend fun TelegramFlow.removeNotificationGroup(notificationGroupId: Int, maxNotificationId: Int) =
    this.sendFunctionLaunch(TdApi.RemoveNotificationGroup(notificationGroupId, maxNotificationId))

/**
 * Suspend function, which removes a notification sound from the list of saved notification sounds.
 *
 * @param notificationSoundId Identifier of the notification sound.
 */
suspend fun TelegramFlow.removeSavedNotificationSound(notificationSoundId: Long) =
    this.sendFunctionLaunch(TdApi.RemoveSavedNotificationSound(notificationSoundId))

/**
 * Suspend function, which resets all chat and scope notification settings to their default values.
 * By default, all chats are unmuted and message previews are shown.
 */
suspend fun TelegramFlow.resetAllNotificationSettings() =
    this.sendFunctionLaunch(TdApi.ResetAllNotificationSettings())

/**
 * Suspend function, which changes notification settings for reactions.
 *
 * @param notificationSettings The new notification settings for reactions.
 */
suspend
    fun TelegramFlow.setReactionNotificationSettings(notificationSettings: ReactionNotificationSettings?)
    = this.sendFunctionLaunch(TdApi.SetReactionNotificationSettings(notificationSettings))

/**
 * Suspend function, which changes notification settings for chats of a given type.
 *
 * @param scope Types of chats for which to change the notification settings.  
 * @param notificationSettings The new notification settings for the given scope.
 */
suspend fun TelegramFlow.setScopeNotificationSettings(scope: NotificationSettingsScope?,
    notificationSettings: ScopeNotificationSettings?) =
    this.sendFunctionLaunch(TdApi.SetScopeNotificationSettings(scope, notificationSettings))
