//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.coroutines

import kotlin.Long
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.td.libcore.telegram.TdApi
import org.drinkless.td.libcore.telegram.TdApi.InputFile

/**
 * Suspend function, which deletes a profile photo. If something changes, updateUser will be sent.
 *
 * @param profilePhotoId Identifier of the profile photo to delete.
 */
suspend fun TelegramFlow.deleteProfilePhoto(profilePhotoId: Long) =
    this.sendFunctionLaunch(TdApi.DeleteProfilePhoto(profilePhotoId))

/**
 * Suspend function, which uploads a new profile photo for the current user. If something changes,
 * updateUser will be sent.
 *
 * @param photo Profile photo to set. inputFileId and inputFileRemote may still be unsupported.
 */
suspend fun TelegramFlow.setProfilePhoto(photo: InputFile?) =
    this.sendFunctionLaunch(TdApi.SetProfilePhoto(photo))
