//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.coroutines

import kotlinx.telegram.core.TelegramFlow
import org.drinkless.td.libcore.telegram.TdApi
import org.drinkless.td.libcore.telegram.TdApi.PremiumFeature
import org.drinkless.td.libcore.telegram.TdApi.PremiumFeatures
import org.drinkless.td.libcore.telegram.TdApi.PremiumSource

/**
 * Suspend function, which returns information about features, available to Premium users.
 *
 * @param source Source of the request; pass null if the method is called from some non-standard
 * source.
 *
 * @return [PremiumFeatures] Contains information about features, available to Premium users.
 */
suspend fun TelegramFlow.getPremiumFeatures(source: PremiumSource?): PremiumFeatures =
    this.sendFunctionAsync(TdApi.GetPremiumFeatures(source))

/**
 * Suspend function, which informs TDLib that the user viewed detailed information about a Premium
 * feature on the Premium features screen.
 *
 * @param feature The viewed premium feature.
 */
suspend fun TelegramFlow.viewPremiumFeature(feature: PremiumFeature?) =
    this.sendFunctionLaunch(TdApi.ViewPremiumFeature(feature))
