//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.coroutines

import kotlin.Long
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.td.libcore.telegram.TdApi
import org.drinkless.td.libcore.telegram.TdApi.ProfileTab

/**
 * Suspend function, which changes the main profile tab of the current user.
 *
 * @param mainProfileTab The new value of the main profile tab.
 */
suspend fun TelegramFlow.setMainProfileTab(mainProfileTab: ProfileTab?) =
    this.sendFunctionLaunch(TdApi.SetMainProfileTab(mainProfileTab))

/**
 * Suspend function, which changes the main profile tab of the channel; requires canChangeInfo
 * administrator right.
 *
 * @param supergroupId Identifier of the channel.  
 * @param mainProfileTab The new value of the main profile tab.
 */
suspend fun TelegramFlow.setSupergroupMainProfileTab(supergroupId: Long,
    mainProfileTab: ProfileTab?) =
    this.sendFunctionLaunch(TdApi.SetSupergroupMainProfileTab(supergroupId, mainProfileTab))
