//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.coroutines

import kotlin.ByteArray
import kotlin.Long
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.td.libcore.telegram.TdApi
import org.drinkless.td.libcore.telegram.TdApi.ReportSponsoredResult
import org.drinkless.td.libcore.telegram.TdApi.VideoMessageAdvertisements

/**
 * Suspend function, which informs TDLib that the user clicked a video message advertisement.
 *
 * @param advertisementUniqueId Unique identifier of the advertisement.
 */
suspend fun TelegramFlow.clickVideoMessageAdvertisement(advertisementUniqueId: Long) =
    this.sendFunctionLaunch(TdApi.ClickVideoMessageAdvertisement(advertisementUniqueId))

/**
 * Suspend function, which returns advertisements to be shown while a video from a message is
 * watched. Available only if messageProperties.canGetVideoAdvertisements.
 *
 * @param chatId Identifier of the chat with the message.  
 * @param messageId Identifier of the message.
 *
 * @return [VideoMessageAdvertisements] Contains a list of advertisements to be shown while a video
 * from a message is watched.
 */
suspend fun TelegramFlow.getVideoMessageAdvertisements(chatId: Long, messageId: Long):
    VideoMessageAdvertisements = this.sendFunctionAsync(TdApi.GetVideoMessageAdvertisements(chatId,
    messageId))

/**
 * Suspend function, which reports a video message advertisement to Telegram moderators.
 *
 * @param advertisementUniqueId Unique identifier of the advertisement.  
 * @param optionId Option identifier chosen by the user; leave empty for the initial request.
 *
 * @return [ReportSponsoredResult] This class is an abstract base class.
 */
suspend fun TelegramFlow.reportVideoMessageAdvertisement(advertisementUniqueId: Long,
    optionId: ByteArray?): ReportSponsoredResult =
    this.sendFunctionAsync(TdApi.ReportVideoMessageAdvertisement(advertisementUniqueId, optionId))

/**
 * Suspend function, which informs TDLib that the user viewed a video message advertisement.
 *
 * @param advertisementUniqueId Unique identifier of the advertisement.
 */
suspend fun TelegramFlow.viewVideoMessageAdvertisement(advertisementUniqueId: Long) =
    this.sendFunctionLaunch(TdApi.ViewVideoMessageAdvertisement(advertisementUniqueId))
